const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
    title: 'Harness',
  });

  // In dev, load from Vite; in prod from built index.html
  if (process.env.VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(process.env.VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(path.join(__dirname, 'index.html'));
  }

  // Open devtools in dev
  if (process.env.VITE_DEV_SERVER_URL) {
    mainWindow.webContents.openDevTools();
  }
}

app.whenReady().then(() => {
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

// Example IPC for future agent calls or bridge
ipcMain.handle('agent-generate-html', async (event, prompt) => {
  // This would call real agent in full impl
  // For now, return a rich HTML based on prompt
  return generateMockHtmlResponse(prompt);
});

function generateMockHtmlResponse(prompt) {
  // Simulate agent using HTML_CONTRACT logic: produce rich, interactive HTML
  const safePrompt = prompt.replace(/</g, '&lt;').replace(/>/g, '&gt;');
  let content = `
    <div style="padding: 20px; font-family: system-ui;">
      <h2>Agent Response to: ${safePrompt}</h2>
      <p>This is a self-contained interactive HTML card generated by the harness agent (following HTML_CONTRACT).</p>
      <div style="border: 1px solid #ccc; padding: 10px; margin: 10px 0;">
        <button onclick="alert('Interactivity works inside the card! This demonstrates HTML as first-class UI.');">Click for action</button>
        <p>Progress: <progress value="75" max="100"></progress> 75%</p>
      </div>
    </div>
  `;
  if (prompt.toLowerCase().includes('plan') || prompt.toLowerCase().includes('todo')) {
    content = `
      <div style="padding: 20px;">
        <h3>Interactive Plan: ${safePrompt}</h3>
        <ul>
          <li><input type="checkbox"> Task 1 from your prompt</li>
          <li><input type="checkbox" checked> Task 2</li>
        </ul>
        <button onclick="this.innerText='Updated!';">Update plan</button>
      </div>
    `;
  }
  // Full standalone HTML for the card
  return `<!doctype html><html><head><style>body { font-family: system-ui; background: #f8fafc; margin:0; padding:10px; }</style></head><body>${content}</body></html>`;
}
